Better i35 support
dahlb/ha_blueair pull request #142
Opened 2024-11-27 00:28 UTC by rainwoodman

Will update.

2024-11-27 00:30 UTC, rainwoodman commented on custom_components/ha_blueair/blueair_aws_data_update_coordinator.py
> +        if self.model == ModelEnum.HUMIDIFIER_I35:
I debated if this divergence qualifies for a new subclass; and my sense is not quite. What do you think?

2024-11-27 13:49 UTC, dahlb requested changes

2024-11-27 13:49 UTC, dahlb commented on custom_components/ha_blueair/blueair_aws_data_update_coordinator.py
> +        await self.async_request_refresh()
this change to calling async_request_refresh circumvents the ha playform's enabled flag
```
    async def async_update(self) -> None:
        """Update the entity.

        Only used by the generic entity update service.
        """
        # Ignore manual update requests if the entity is disabled
        if not self.enabled:
            return

        await self.coordinator.async_request_refresh()
```

and the sleep 5 was in there to ensure the blueair api had time to propagate the updated state because it doesn't seem to do it synchronously on blueair's side

2024-11-27 13:49 UTC, dahlb commented on custom_components/ha_blueair/fan.py
> +_DEFAULT_FAN_SPEED_PERCENTAGE = 50
let's through this in the const file

2024-11-27 18:24 UTC, rainwoodman commented on custom_components/ha_blueair/blueair_aws_data_update_coordinator.py
> +        await self.async_request_refresh()
I see. 

I recall the five second delay is configurable when we create the bouncer. async_request_refresh has the advantage of batching multiple refreshes with in the cooling off window (10 seconds). Let me poke with that -- My experience is using async_request_refresh improved the responsiveness overall, since I tend to tweak the fan speed multiple times in a row.

The enabled flag is an entity level attribute. Let me make sure the entities are calling `self.async_update()`.  (I confused async_update with async_refresh initially as well). I will post an update later.

2024-11-28 07:18 UTC, rainwoodman commented on custom_components/ha_blueair/blueair_aws_data_update_coordinator.py
> +        await self.async_request_refresh()
Please take a look.

* I updated the debouncer to follow the 5 seconds delay.
* I updated entities.py::async_update to include the self.enabled check as you suggested. Although I don't know how to observe the effect of this change: If a entity is disabled, then I don't know how to trigger an update from the UI.

2024-11-28 07:19 UTC, rainwoodman commented on custom_components/ha_blueair/fan.py
> +_DEFAULT_FAN_SPEED_PERCENTAGE = 50
Done.

2024-11-28 07:38 UTC, dahlb commented on custom_components/ha_blueair/blueair_aws_data_update_coordinator.py
> +        if self.model == ModelEnum.HUMIDIFIER_I35:
I agree it's possible, but I'm also okay with keeping them unified for now at least

2024-11-28 07:56 UTC, dahlb requested changes

2024-11-28 07:56 UTC, dahlb commented on custom_components/ha_blueair/blueair_aws_data_update_coordinator.py
> +_FILTER_EXPIRED_THRESHOLD = 95
please move this to const with the others

2024-11-28 07:56 UTC, dahlb commented on custom_components/ha_blueair/manifest.json
> +  "requirements": ["blueair-api==1.10.1"],
1.11.0 was the release made by the github hooks

2024-11-28 09:04 UTC, rainwoodman commented on custom_components/ha_blueair/blueair_aws_data_update_coordinator.py
> +_FILTER_EXPIRED_THRESHOLD = 95
Done.

2024-11-28 09:04 UTC, rainwoodman commented on custom_components/ha_blueair/manifest.json
> +  "requirements": ["blueair-api==1.10.1"],
Done.

2024-11-28 13:24 UTC, merged